WIP: V1.5
alephium/www pull request #82
Opened 2022-05-10 20:28 UTC by lf94

2022-05-17 19:29 UTC, lf94 commented
The test is failing on a positive: that link, when clicked from the test, is not 404...

2022-05-19 14:41 UTC, nop33 requested changes
Good job @lf94! I hope you don't take my review very critically, this is what I do best, so I am very critical about implementing designs 😇  Code review will follow once I am happy with visual, functional, and performance stuff.

## Visual and functional review
1. The night sky background does not expand to the whole width of the screen and it creates a sharp cut
![image](https://user-images.githubusercontent.com/1579899/169310580-1da2ce6e-d514-4d4e-aeb1-7100d1f9ca75.png)
1. The team and career links are not working properly
    <img width="240" alt="image" src="https://user-images.githubusercontent.com/1579899/169311240-d5bdb309-b9a7-45ae-ae7b-9696eaa779f9.png">
1. All font sizes and image dimensions all across the website are not accurate with the designs. Example:
![image](https://user-images.githubusercontent.com/1579899/169313272-da0463d1-ce28-481e-bfdf-b35248519740.png)
1. In the designs, the cards take all available content space (full content width). In the implementation the are aligned to the left 
    <img width="1728" alt="image" src="https://user-images.githubusercontent.com/1579899/169314935-e240e4e1-73c4-4a16-a103-ad262bd91994.png">
1. Confetti background is missing in milestones section
1. The year is not sticky when scrolling (see [here for example](https://www.simoninstitute.ch/project/longterm-governance-network/))
1. Rows don't expand to full width of screen, like in figma 
    <img width="1728" alt="image" src="https://user-images.githubusercontent.com/1579899/169317681-bcb5374b-42a0-4153-b35a-159feda6dd91.png">
1. testnet launch is not highlighted 
    <img width="292" alt="image" src="https://user-images.githubusercontent.com/1579899/169317892-259040a9-e029-4b5f-ad9a-baa5a1523e67.png">
1. More spacing is needed between the title and the date (probably a `line-height` issue) 
    <img width="667" alt="image" src="https://user-images.githubusercontent.com/1579899/169318418-4685b99e-8fea-496b-afc4-adbe00d2ce58.png">
1. Not enough spacing between sections 
    <img width="1036" alt="image" src="https://user-images.githubusercontent.com/1579899/169318778-2faad4ee-fdc4-4a59-8c81-73dc9ab72583.png">
1. Cards have unequal size: 
    <img width="490" alt="image" src="https://user-images.githubusercontent.com/1579899/169318982-adc85cd0-831a-470f-899d-021fbf794aa3.png">
1. Mobile 
    <img width="430" alt="image" src="https://user-images.githubusercontent.com/1579899/169319943-401ac80f-75c7-4cef-9136-9088b9c41dff.png"> 
    <img width="406" alt="image" src="https://user-images.githubusercontent.com/1579899/169320095-319cc377-e869-4a5f-9f24-48396a726191.png">

## Performance review
1. Performance slightly worsened  
    Live website 
    <img width="708" alt="image" src="https://user-images.githubusercontent.com/1579899/169322583-8ce95316-8e6b-495b-8529-62e9129a74a2.png">
    
    PR code after building and serving with `npx http-server`: 
    <img width="713" alt="image" src="https://user-images.githubusercontent.com/1579899/169322765-99009923-493c-4e74-b6ea-00ca998288e5.png">
2. Console errors reduce best practices score (CSP needs to be updated)

## Comments about things not present in Figma
1. Technology page is not accessible from anywhere
1. Technology page has no navigation menu

## Questions
1. Is usability section now gone for good?
1. Technology section is still present even though there's a subpage for it, is this intended?

2022-05-19 17:13 UTC, lf94 commented
Would you happen to know how to export the night sky background from Figma without it cutting off? I thought originally it too was the element clipping it, but it's the actual SVG...!

2022-05-24 10:54 UTC, nop33 commented
> Would you happen to know how to export the night sky background from Figma without it cutting off? I thought originally it too was the element clipping it, but it's the actual SVG...!

Normally, through the Figma app, @mvaivre has given me "edit" rights, which allows me to properly export assets (even if they are cut-off). @mvaivre, could you add the website project on Figma as well, so that I can export what @lf94 needs?

2022-05-24 12:34 UTC, mvaivre commented
First of all, thanks @lf94 for the work and @nop33 for the thorough hands-on review!

> Confetti background is missing in milestones section

We discussed this with Lee and it's normal. This was a "placeholder" for a potential animation I'm not so sure about. So we start without it 👌 

> could you add the website project on Figma as well

Done!

2022-05-24 12:38 UTC, mvaivre commented
> Is usability section now gone for good?

Unfortunately, it's gone for now, as the marketing team feared the this would make the page too long. I'm hopeful to get it back as a standalone download page though, because it's nice.

> Technology section is still present even though there's a subpage for it, is this intended?

The marketing team decided to have a (slightly) more condensed tech section on the landing page (with no tips boxes & "see more" links), plus a standalone page reusing the previous content. I'm personally not 100% convinced by this approach, but we can iterate easily if needed. Let's see how this looks.

2022-05-25 09:29 UTC, nop33 commented
> Would you happen to know how to export the night sky background from Figma without it cutting off? I thought originally it too was the element clipping it, but it's the actual SVG...!

Here are the assets you need. I provide you with 3 different ones: sky, eclipse, and one that combines them both. Idk how you prefer implementing it, feel free to choose!

<details><summary>Click here to see assets</summary>

## stars
![stars](https://user-images.githubusercontent.com/1579899/170230120-10882c8e-9520-4421-b5b6-d22578f34e4e.svg)

## eclipse
![eclipse](https://user-images.githubusercontent.com/1579899/170230131-62fbf8fe-752a-4e90-b1ea-354458bb9bcf.svg)

## eclipse with stars
![eclipse-with-stars](https://user-images.githubusercontent.com/1579899/170230139-7a8bb9a3-998f-4656-bed0-96603a915c0a.svg)

</details>

2022-05-26 22:09 UTC, LeeAlephium commented
1-5 is addressed (either by Mika or via code), 7-12 is addressed (same), CSP issue is addressed (so best practices score should be back up)

Technology page is still not accessible; I haven't been told how we should go there yet (nor how people will get back to the home page from there, as you noted)... We can do additional PRs though once things are figured out for this piece...

The only thing which really remains is 6 (sticky years). Even re-arranging the DOM does not help me - I think it has to live way too high up the DOM to which it won't be styled correctly if it is. I really don't know what to do.

All right then, let's do another round...! The long format you're doing is working well :)

2022-05-31 07:15 UTC, nop33 commented
> All right then, let's do another round...!

Is this a request for review? Would be useful if you would press the "re-request review" button in such cases! (no need for this time) Thanks!

<img width="355" alt="image" src="https://user-images.githubusercontent.com/1579899/171114481-b0ce1e93-94ce-4064-8396-a251b3ff7788.png">

2022-05-31 07:33 UTC, mvaivre commented on src/styles/themes.ts
> +export const oppositeThemeOf = (theme) => (theme === darkTheme ? lightTheme : darkTheme)
This causes an editor error linked to type: `any`.

<img width="496" alt="image" src="https://user-images.githubusercontent.com/6715943/171117885-40abee21-1d8b-463f-bdfc-cb93f541fb6e.png">


Also, this is not used anywhere, so what should we do with it? :)

2022-05-31 07:35 UTC, mvaivre commented on src/styles/themes.ts
> +  bgPrimary: 'var(--color-grey-900)',
If 2 theme variables end up having the same value, it's probably that we don't use them properly. I'll see how to streamline this situation!

2022-05-31 09:24 UTC, mvaivre commented on src/styles/themes.ts
> +export const oppositeThemeOf = (theme) => (theme === darkTheme ? lightTheme : darkTheme)
Actually, seems like your local typescript compiler isn't screaming at you? Mine is upset :D 

<img width="622" alt="image" src="https://user-images.githubusercontent.com/6715943/171140438-7d0056e2-8d75-449e-8492-b696613b2ef0.png">

2022-05-31 13:17 UTC, mvaivre commented on src/components/DualTimeline.tsx
> +const LineStartsEnds = ({ headings, starts, ends, isSingle, height }) =>
No types, conditional props?

2022-05-31 13:17 UTC, mvaivre commented on src/components/DualTimeline.tsx
> +let Year = ({ value, headings, isSingle }) =>
We're mixing components and styles. Our internal rule so far, was to keep all stylings at the end of the file.

2022-06-06 09:26 UTC, nop33 commented on package.json
> +    "@alephium/sdk": "^0.0.6",
```suggestion
    "@alephium/sdk": "0.0.6",
```

2022-06-06 09:26 UTC, nop33 commented on src/components/DualTimeline.tsx
> +    `
Although this is correct, using `css` would improve the code highlighting
```suggestion
    css`
```

2022-06-06 09:26 UTC, nop33 commented on src/utils/index.tsx
> +}
Did we implement something like this for the stats in the explorer? Maybe a good candidate for the js-sdk?

2022-06-06 09:43 UTC, nop33 commented on src/components/PageSectionNumbers.tsx
> +      description: 'alph circulating'
Looks weird with lower case:

<img width="1218" alt="image" src="https://user-images.githubusercontent.com/1579899/172136972-275572fb-5712-40a6-b63a-813edd2ebae5.png">

```suggestion
      description: 'ALPH circulating'
```

2022-06-06 09:47 UTC, nop33 commented
<img width="568" alt="image" src="https://user-images.githubusercontent.com/1579899/172137775-c9beeffd-f39f-41c3-8f2b-fb8670b09898.png">

2022-06-28 08:23 UTC, mvaivre commented
I think we can close this one, as it's superseded by #83. Thanks for your work!

2022-06-28 08:23 UTC, closed without merging